name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install uvicorn

    - name: Install Nginx
      run: sudo apt-get install -y nginx

    - name: Configure Nginx
      run: |
        sudo rm /etc/nginx/sites-enabled/default
        sudo cp ./.github/nginx.conf /etc/nginx/sites-available/fastapi
        sudo ln -s /etc/nginx/sites-available/fastapi /etc/nginx/sites-enabled/
        sudo nginx -t
        sudo systemctl restart nginx

    - name: Start FastAPI application
      run: |
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
